### ISSUE TITLE
Please port this plugin to Quasar framework.

### ISSUE THREAD

**Issue by tanthammar** [ktsn/vue-cli-plugin-auto-routing#19]
I tried, but It is above my knowledge level :)
Would be super happy if you could make this plugin for Quasar.

https://quasar.dev/
https://quasar.dev/app-extensions/development-guide/introduction

**Comment by ktsn** [comment]
Because vue-cli-plugin-auto-routing consists of [vue-auto-routing webpack plugin](https://github.com/ktsn/vue-auto-routing), you can extend your webpack config via `build.extendConfig` in the quasar config to add the plugin.

https://quasar.dev/quasar-cli/cli-documentation/handling-webpack

it would be:

```js
// quasar.conf.js
const VueAutoRoutingPlugin = require('vue-auto-routing/lib/webpack-plugin')
```

```js
build: {
  extendWebpack (cfg, { isServer, isClient }) {
    cfg.module.plugins.push(
      new VueAutoRoutingPlugin({
        pages: 'src/pages',
        importPrefix: '@/pages/'
      })
    )
  }
}
```

**Comment by tanthammar** [comment]
Thank you for your suggestion.
Get this error 
```
 app:webpack Extending SPA Webpack config +6ms
(node:41598) UnhandledPromiseRejectionWarning:   TypeError: Cannot read property 'push' of undefined
```

**Comment by ktsn** [comment]
Then you should simply assign an array having the plugin instance into module.plugins instead of using module.plugins.push. 

```js
cfg.module.plugins = [
  new VueAutoRoutingPlugin(...)
]
```
