### ISSUE TITLE
vite suport

### ISSUE THREAD

**Issue by transtone** [ktsn/vue-cli-plugin-auto-routing#60]
Is there a plan to support vite?
like these: https://github.com/vitejs/awesome-vite#routing

**Comment by ghost** [comment]
Hi i need your help in my Jarvis program. Because there is a problem i don't know how. please help me.
that's my code:-
[main.docx](https://github.com/ktsn/vue-cli-plugin-auto-routing/files/6371836/main.docx)
And that's my output:-
[OUTPUT.docx](https://github.com/ktsn/vue-cli-plugin-auto-routing/files/6371838/OUTPUT.docx)

Thanks you
