### ISSUE TITLE
When you want to generate a route, the path field can be turned into lowercase, and the default home page is lowercase index.vue want to be compatible with uppercase Index.vue or Home.vue,home.vue

### ISSUE THREAD

**Issue by liuhuanhui** [ktsn/vue-cli-plugin-auto-routing#8]
When you want to generate a route, the path field can be turned into lowercase, and the default home page is lowercase index.vue want to be compatible with uppercase Index.vue or Home.vue,home.vue

**Comment by liuhuanhui** [comment]
or increase the configuration item when it is generated

**Comment by ktsn** [comment]
I thought about this before but I won't add such path transformation because:

1. URL path name is case sensitive
2. Various users have their own path convention (/foo-bar, /foobar, /foo_bar, etc.). Dealing with various case would complicate the implementation.

Simply exclude page component from the name convention is enough to me. It is very clear rule and there should be no real issue I guess.
